Please download dataset file "treecover_loss__ha 1" to your local computer 
replace the correct path of file "treecover_loss__ha 1" from your local system post download in spyder file code in here "df_treeloss_drivers=pd.read_csv('C:/Users/prave/OneDrive - University of Hertfordshire/Applied DS 1/Tree loss due to fire/Tree cover loss due to fires in United Kingdom/treecover_loss__ha 1.csv',index_col='Tree cover loss year')" before run the code to get output without any error.    
